# Generated by Django 3.2.2 on 2023-07-31 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=100)),
                ('category', models.CharField(choices=[('Furniture', 'Furniture'), ('Appliances', 'Appliances'), ('Decor', 'Decor'), ('Tools', 'Tools')], max_length=100)),
                ('desc', models.FloatField(max_length=200)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('contact', models.PositiveIntegerField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Best_Deals',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.product')),
            ],
        ),
    ]
