# Generated by Django 3.2.2 on 2023-07-31 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsored',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.product')),
            ],
        ),
    ]
