# Generated by Django 3.2.2 on 2023-08-11 23:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230810_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='contact',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 10', regex='^.{9}$')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(max_length=200),
        ),
    ]
