# Generated by Django 3.2.2 on 2023-08-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20230812_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
